### ISSUE TITLE
D-NOISE Export doesn't always show the Image after render is finished with Advanced settings enabled

### ISSUE THREAD

**Issue by djjulzen** [grantwilk/d-noise#23]
So I'm testing a blender project that I made through watching a tutorial for 2 years ago from sRGB color space now I'm using Filmic for this and wanted to use the AI-Denoiser.

Everything is installed properly including the Optix Binaries so the only issue is that sometimes the D-NOISE Export shows the final result but in other times if I have the Advanced features like HDR Training and Extra Passes turned on, the D-NOISE Export shows nothing once the render is finished.

Here's a screenshot showing what exactly what's going on
https://gyazo.com/e1969224c26f844e53eb61b49b4edde0

**Comment by grantwilk** [comment]
Can you find a pattern that causes this to bug to occur? I'm trying to replicate the issue on my end but I'm not seeing the same behavior.

**Comment by grantwilk** [comment]
Is Blender throwing any errors in the console?

**Comment by djjulzen** [comment]
Nope, no errors at all.

I've tried the official version of 2.79b and the daily build 2.79.6 master no difference there either.

It should be denoising automatically and showing the result afterwards right? Even with the advanced setting enabled?

**Comment by djjulzen** [comment]
Anyways I deleted the D-NOISE from blender and the blender folders, then reinstalled the D-NOISE addon, installed the Optix binaries again hopefully it'll denoise automatically with the advanced settings turned on

**Comment by djjulzen** [comment]
>           Can you find a pattern that causes this to bug to occur? I'm trying to replicate the issue on my end but I'm not seeing the same behavior.

Other projects seem to have different results apparently not sure what the core cause of it is but here's another screenshot of a project that actually worked, not sure why others don't on my end but this one works every time with HDR Training and Extra Passes enabled

https://gyazo.com/3d5504b2769181e02d70ccbcc6f6cacc

**Comment by Vitoria90** [comment]
I'm getting the same issue. I have a project that in one render had D-Noise work fine, and on every subsequent render the result either comes up empty or as a fully black image.
Eventually I got it to work by removing any nodes that used the D-Noise Export and connecting my Render Result to the Composite node with nothing else between it, and doing a Quick D-Noise. However, it took a few tries to even get that to work, so keep that in mind.

**Comment by djjulzen** [comment]
That's good to know. I'm doing new projects on blender 2.8 so I'll see how
it goes for me after the changes in D-NOISE

**Comment by marcinkulaga** [comment]
I made some tests and I still don't know why, but if it doesn't work just make new Blend file and import all things to that new file. Then It works again.
