### ISSUE TITLE
Weird split screen after render?

### ISSUE THREAD

**Issue by dannyduque** [grantwilk/d-noise#31]
Hi Grant! I just want to say that this is an amazing add-on and I'm just amazed but I'm having just one problem with it that's really bumming me out! For some reason when I render I get this sort of split screen in some areas. This happen when I try using the blend option. Here's my render at 75 samples, I've tried turning the advanced options on and also straightening camera as it's rotated but to no avail. If I could know how to fix it this I would be eternally grateful as this denoiser is great and will save me lots of render time. Thank you!
![source](https://user-images.githubusercontent.com/46237861/50534699-71e82e00-0b0e-11e9-9d7e-3ffa97a9ecad.png)
EDIT: I should also mention that this is an animation I'm working on and I'm pretty scared to do the final render and have a couple of images split this way, thanks again. :)
Here's another example with almost the entire screen split:
![source2](https://user-images.githubusercontent.com/46237861/50534774-a4465b00-0b0f-11e9-944e-d802787e1920.png)

**Comment by grantwilk** [comment]
That's really peculiar. Are you using multiple render layers or any compositing effects?

**Comment by dannyduque** [comment]
Hi Grant, thanks for your reply! I am not sure if I have compositing
effects or different layers. Do you mean having multiple objects in
different layers and then combining them to render? If so, then I have done
that for this scene so maybe I can try that. Like I siad, sometimes it goes
away but might come back in a different frame. It's very odd. I've tried
multiple things on my end, maybe I'm not doing something wrong?

**Comment by Treazure** [comment]
I too am getting this issue. It is happening with stand alone image files as well. It happens when using any "D-Noise Blend" amount above 0. It seems to have misaligned the original "noisy" image over top of the D-Noised image.
![image](https://user-images.githubusercontent.com/44760644/58949382-eaa08580-8751-11e9-85c6-5cfb5ee8d844.png)

**Comment by jatoja1717** [comment]
I have exactly the same problem. ;(
Looking for help.

![image](https://user-images.githubusercontent.com/57195977/67893576-1ab05100-fb57-11e9-9d90-3a17ca734e5d.png)
