### ISSUE TITLE
Add option for Optix binaries path

### ISSUE THREAD

**Issue by filibis** [grantwilk/d-noise#7]
Hi Grant,

Is it possible to add an option to indicate Optix binaries path instead of downloading it? I already have it in my drive (from [this addon](https://github.com/troopy28/OptiX-Denoiser-for-Blender)), so it would be great to enable it without redownloading. (I assume they are not different versions of Optix, are they?)

Thanks for creating the addon,

Emir

**Comment by hansnolte** [comment]
I agree with filibis.

If you have several Blenderbuilds (Fracture, Mantaflow etc.) on your Drive it's quite a waste of space.

And second:
If you have Blender on an SSD and you render long animations, the Denoiser will write you gigabytes of 
temporary EXR files on the SSD. It's too bad about that.
