### ISSUE TITLE
Denoiser don't close after when he's done.

### ISSUE THREAD

**Issue by hansnolte** [grantwilk/d-noise#8]
After denoising the Denoiser.exe still running in the background and blocks Blender.
When I shoot the Denoiser with the Taskmanager, Blender reacts again and shows me the noiseless image.

Win 7 Pro 64 Bit
Blender 2.79
GTX 1070 (Newest Driver)

**Comment by hikaruAi** [comment]
Happens here too, i have to manually kill the process and enable the Eye icon in the UV Editor

**Comment by xtvjxk123456** [comment]
me too, blender blocked,

**Comment by AndreasReschGFX** [comment]
Same here. When I hit Quick D-Noise, Blender hangs. After I kill the process in the Task Manager, the denoised image shows in the viewport.

Win 7 x64
Geforce GTX 1060 + Geforce GTX 770

**Comment by rainerli22** [comment]
Same with me
Win 7 x64, Gforce GTX 1070, newest Nvidia drivers
have to wait until the blue "busy circle" appears, then I can kill denoisser.exe process and Blender 7.79 comes back to life, showing the nicely denoised render. 
Same with Blender version 2.8, but with Win 10 on the same hardware everything works fine.

**Comment by gatzkerob** [comment]
Same here.

When render is finished, D-Noise does nothing.

Attempting to click on any Blender window causes Blender to become unresponsive. 

Checking task manager, I see multiple "Denoiser.exe" processes from previous attempts. 

I'm using D-Noise with no extra settings. 

Supported Feature Set + Branched Path Tracing.

Blender 2.80
Windows 7 Pro 64-bit
EVGA 2080 Ti
AMD FX-8350 CPU
32 GB RAM
